package com.aixoft.escassandra.model;

import com.aixoft.escassandra.aggregate.Aggregate;

/**
 * The aggregate snapshot command interface.
 *
 * @param <T> the type of aggregate data.
 */
public interface SnapshotCommand<T> {

    /**
     * Validates snapshot command against aggregate data.
     * If validation returns 'false' then command will be ignored
     * and no {@link SnapshotEvent} will be published on the aggregate.
     * <p>
     * Method can throw an exception to indicate failure and break processing chain.
     *
     * @param aggregateData the aggregate data.
     * @return the result of validation.
     */
    default boolean validate(Aggregate<T> aggregateData) {
        return true;
    }

    /**
     * Converts command to event.
     *
     * @return the event generated by command.
     */
    SnapshotEvent<T> toEvent();
}
