# This is a sample build configuration for Java (Maven).
# Check our guides at https://confluence.atlassian.com/x/zd-5Mw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: openjdk:14.0.2-oraclelinux8

clone:
  depth: full              # SonarCloud scanner needs the full history to assign issues properly

definitions:
  caches:
    sonar: ~/.sonar/cache  # Caching SonarCloud artifacts will speed up your build
  services:
    cassandra:
      image: cassandra
      environment:
        MAX_HEAP_SIZE: 512M # Need to restrict the heapsize or else Cassandra will OOM
        HEAP_NEWSIZE: 128M
  steps:
    - step: &build-test-sonarcloud
        name: Build, test and analyze on SonarCloud
        caches:
          - maven
          - sonar
        script:
          - ./mvnw -B org.jacoco:jacoco-maven-plugin:prepare-agent verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
        services:
          - cassandra
        artifacts:
          - target/**
    - step: &build-test
        name: Build and test
        caches:
          - maven
        script:
          - ./mvnw -B verify
        artifacts:
          - target/**
        services:
          - cassandra
pipelines:
  branches:
    master:
      - step: *build-test-sonarcloud
      - step: *build-test
    development:
      - step: *build-test-sonarcloud
      - step: *build-test
  pull-requests:
    '**':
      - step: *build-test-sonarcloud
      - step: *build-test
